In [ ]:
import numpy as np
arr = np.array([10,20,30])
print(arr)

arr = np.array([[10,20,30],[40,50,60]])
print(arr)


[10 20 30]
[[10 20 30]
 [40 50 60]]


In [4]:
arr = np.array([10,20,30,40],ndmin=3)
print(arr)

[[[10 20 30 40]]]


In [5]:
arr = np.array([10,20,30], dtype=float)
print(arr)

[10. 20. 30.]


In [12]:

arr = np.array([10,20,30])
print(arr.itemsize)
print(arr.size * arr.itemsize)


8
24


In [ ]:
#shape and size
arr = np.array([[10,20,30,40],[50,60,70,80]])

print(arr.size)      #total elememnts
print(arr.shape)       #rows, columns

8
(2, 4)


In [14]:
lst = [10,20,30]
arr = np.array(lst)
print(arr)

[10 20 30]


In [15]:
import numpy as np
 
# Creating a rank 1 Array
arr = np.array([1, 2, 3])
print(arr)
 
# Creating a rank 2 Array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr)
 
# Creating an array from tuple
arr = np.array((1, 3, 2))
print(arr)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[1 3 2]
