In [2]:
import numpy as np

#Create a 5x3 array of random scores (50–100)
scores = np.random.randint(50, 101, size=(5, 3))

#Column-wise mean (mean score per subject)
mean_scores = scores.mean(axis=0)

#Subtract mean using broadcasting
centered_scores = scores - mean_scores

# Output
print("Original scores:\n", scores)
print("\nMean per subject:\n", mean_scores)
print("\nCentered scores:\n", centered_scores)


Original scores:
 [[98 94 62]
 [63 73 71]
 [76 93 70]
 [63 60 89]
 [96 72 89]]

Mean per subject:
 [79.2 78.4 76.2]

Centered scores:
 [[ 18.8  15.6 -14.2]
 [-16.2  -5.4  -5.2]
 [ -3.2  14.6  -6.2]
 [-16.2 -18.4  12.8]
 [ 16.8  -6.4  12.8]]
